/*************************************************************************
* 
*  Filename:             mdemo.h
*                  
*  Description:          This file contains global constants, variables
*                        and function prototypes for the mdemo.c file
*			 and the mdemo.rc file.
*
*************************************************************************/
#ifndef MDEMO_H
#define MDEMO_H

/******************* MENU IDENTIFIERS ***********************************/
#define IDM_MAIN             	257
#define IDM_GOFAST		258
#define IDM_GOSLOW		259
#define IDM_STOP		260
#define IDM_EXITPROG         	261

/******************* RESOURCE IDENTIFIERS *******************************/
#define ID_NULL              9999
#define ID_WINDOW            256

#endif
